const apis = {
  "background-fetch": {
    name: "Background Fetch API",
    path: "/background-fetch",
  },
  a2key: { name: "Background Tasks", path: "/un" },
  a3key: { name: "Barcode Detection API", path: "/un" },
  a4key: { name: "Battery API", path: "/un" },
  a5key: { name: "Beacon", path: "/un" },
  a6key: { name: "Bluetooth API", path: "/un" },
  a7key: { name: "Broadcast Channel API", path: "/un" },
  a8key: { name: "CSS Counter Styles", path: "/un" },
  a9key: { name: "CSS Font Loading API", path: "/un" },
  a10key: { name: "CSS Painting API", path: "/un" },
  a11key: { name: "CSS Typed Object Model API", path: "/un" },
  a12key: { name: "CSSOM", path: "/un" },
  a13key: { name: "Canvas API", path: "/un" },
  a14key: { name: "Channel Messaging API", path: "/un" },
  a15key: { name: "Clipboard API", path: "/un" },
  a16key: { name: "Console API", path: "/un" },
  a17key: { name: "Contact Picker API", path: "/un" },
  a18key: { name: "Content Index API", path: "/un" },
  a19key: { name: "Credential Management API", path: "/un" },
  a20key: { name: "DOM", path: "/un" },
  a21key: { name: "Encoding API", path: "/un" },
  a22key: { name: "Encrypted Media Extensions", path: "/un" },
  a23key: { name: "EyeDropper API", path: "/un" },
  a24key: { name: "Fetch API", path: "/un" },
  a25key: { name: "File System Access API", path: "/un" },
  a26key: { name: "File and Directory Entries API", path: "/un" },
  a27key: { name: "Fullscreen API", path: "/un" },
  a28key: { name: "Gamepad API ", path: "/un" },
  a29key: { name: "Geolocation API", path: "/un" },
  a30key: { name: "HTML DOM", path: "/un" },
  a31key: { name: "HTML Drag and Drop API", path: "/un" },
  a32key: { name: "HTML Sanitizer API", path: "/un" },
  a33key: { name: "High Resolution Time", path: "/un" },
  a34key: { name: "History API", path: "/un" },
  a35key: { name: "Image Capture API", path: "/un" },
  a36key: { name: "IndexedDB", path: "/un" },
  a37key: { name: "Intersection Observer API", path: "/un" },
  a38key: { name: "Layout Instability API", path: "/un" },
  a39key: { name: "Long Tasks API ", path: "/un" },
  a40key: { name: "Media Capabilities API ", path: "/un" },
  a41key: { name: "Media Capture and Streams", path: "/un" },
  a42key: { name: "Media Session API", path: "/un" },
  a43key: { name: "Media Source Extensions ", path: "/un" },
  a44key: { name: "MediaStream Recording", path: "/un" },
  a45key: { name: "Navigation Timing", path: "/un" },
  a46key: { name: "Network Information API ", path: "/un" },
  a47key: { name: "Page Visibility API", path: "/un" },
  a48key: { name: "Payment Request API", path: "/un" },
  a49key: { name: "Performance API", path: "/un" },
  a50key: { name: "Performance Timeline API", path: "/un" },
  a51key: { name: "Periodic Background Sync", path: "/un" },
  a52key: { name: "Permissions API", path: "/un" },
  a53key: { name: "Picture-in-Picture API", path: "/un" },
  a54key: { name: "Pointer Events", path: "/un" },
  a55key: { name: "Pointer Lock API", path: "/un" },
  a56key: { name: "Presentation API ", path: "/un" },
  a57key: { name: "Proximity Events  ", path: "/un" },
  a58key: { name: "Push API ", path: "/un" },
  a59key: { name: "Resize Observer API", path: "/un" },
  a60key: { name: "Resource Timing API", path: "/un" },
  a61key: { name: "Screen Capture API", path: "/un" },
  a62key: { name: "Screen Orientation API ", path: "/un" },
  a63key: { name: "Screen Wake Lock API", path: "/un" },
  a64key: { name: "Sensor API", path: "/un" },
  a65key: { name: "Server Sent Events", path: "/un" },
  a66key: { name: "Service Workers API", path: "/un" },
  a67key: { name: "Storage", path: "/un" },
  a68key: { name: "Storage Access API", path: "/un" },
  a69key: { name: "Streams ", path: "/un" },
  a70key: { name: "Touch Events", path: "/un" },
  a71key: { name: "URL API", path: "/un" },
  a72key: { name: "URL Pattern API", path: "/un" },
  a73key: { name: "Vibration API", path: "/un" },
  a74key: { name: "Visual Viewport ", path: "/un" },
  a75key: { name: "Web Animations", path: "/un" },
  a76key: { name: "Web Audio API", path: "/un" },
  a77key: { name: "Web Authentication API", path: "/un" },
  a78key: { name: "Web Crypto API", path: "/un" },
  a79key: { name: "Web MIDI API", path: "/un" },
  a80key: { name: "Web Notifications", path: "/un" },
  a81key: { name: "Web Share API", path: "/un" },
  a82key: { name: "Web Speech API", path: "/un" },
  a83key: { name: "Web Storage API", path: "/un" },
  a84key: { name: "Web Workers API", path: "/un" },
  a85key: { name: "WebCodecs API", path: "/un" },
  a86key: { name: "WebGL", path: "/un" },
  a87key: { name: "WebHID API", path: "/un" },
  a88key: { name: "WebRTC", path: "/un" },
  a89key: { name: "WebVR API  ", path: "/un" },
  a90key: { name: "WebVTT", path: "/un" },
  a91key: { name: "WebXR Device API", path: "/un" },
  a92key: { name: "Websockets API", path: "/un" },
  a93key: { name: "Window Controls Overlay API", path: "/un" },
  a94key: { name: "XMLHttpRequest", path: "/un" },
}

export { apis }
